### ISSUE TITLE
In version 3.0.6, the editor of the dark theme has a white background

### ISSUE THREAD

**Issue by ni-ka** [swalladge/sn-themes#1]
used a filter to hide all my notes & tags, the lists are displayed correctly
![Screenshot from 2019-03-12 23-19-54](https://user-images.githubusercontent.com/1225776/54242669-5beae680-451d-11e9-8ba6-6071ed3e454f.png)

**Comment by ni-ka** [comment]
Actually, the fork https://github.com/orestarod/sn-themes works great with 3.0.6 - it's a bit of a different style but it's also a dark theme and looks great.

**Comment by swalladge** [comment]
@ni-ka I no longer use standardnote, and the theme api has unfortunately changed several times over the course of development. I kept up with changes while I was using it for my themes, but I no longer plan to continue maintenance.

**Comment by ni-ka** [comment]
Thanks @swalladge, thanksfully the fork by @orestarod works, so thanks for publishing your work so it could be maintained by someone else!

**Comment by swalladge** [comment]
No worries. Sorry I can't keep maintaining it, but I'm glad someone else has taken over! I'll add a notice in the readme pointing to the fork.

**Comment by orestarod** [comment]
@ni-ka I'm glad the fork was of use to someone other than myself! Be sure to open an issue in case of compatibility breaks as I mainly use standardnotes on browser and don't check on the app very often.
And of course a big thanks to @swalladge for your work :D
